### ISSUE TITLE
Update to MRTK V2.2

### ISSUE THREAD

**Issue by d30tajima** [HoloLabInc/LeapMotionInputForMRTK#3]
MRTK V2.2.0 
Unity 2019.3.0f3
の環境で一部のコードを変更したら動作が確認できたので、報告てがら共有させていただきます．

![image](https://user-images.githubusercontent.com/11310448/71441948-0cda0f00-2747-11ea-90a9-e8501d24cdd4.png)

UpdateInteractions関数の中にあるInputSystemをCoreServices.ImputSystemsに変更したら、動作しました．

**Comment by tarukosu** [comment]
ご報告ありがとうございました。
最新バージョンで MRTK v2.3 に対応させました。
